
show tables;
SELECT * FROM super_store_data;
SELECT * FROM SUPER_STORE_DATA WHERE REGION = 'WEST';
SELECT CATEGORY FROM SUPER_STORE_DATA WHERE SALES > 700;

SELECT * FROM SUPER_STORE_DATA
	WHERE CITY = 'LOS ANGELES' 
	AND SALES > 700 ;
    
    SELECT *
	FROM SUPER_STORE_DATA
	WHERE CITY LIKE 'SAN%';

SELECT SALES, (SALES+50) AS 'WITH_SHIPPING_CHARGES'
FROM SUPER_STORE_DATA;

SELECT  *	
	FROM SUPER_STORE_DATA
	WHERE SALES BETWEEN 2000 AND 5000;
    
    SELECT MIN(PROFIT) AS 'MINIMUM_PROFIT'
    FROM SUPER_STORE_DATA;

SELECT distinct SEGMENT FROM SUPER_STORE_DATA;

select CITY , SUM(PROFIT) AS "TOTAL PROFIT"
FROM SUPER_STORE_DATA
group by CITY
order by CITY DESC
LIMIT 10;

select SALES, SALES+500 AS "INCREASED SALE"
FROM SUPER_STORE_DATA;

select * FROM SUPER_STORE_DATA where quantity IS NULL;

SELECT avg(DISCOUNT) AS AVERAGE_DISCOUNT FROM SUPER_STORE_DATA;
select sum(SALES) AS TOTAL_SALES FROM SUPER_STORE_DATA;

select count(*)
FROM SUPER_STORE_DATA
where CATEGORY = 'TECHNOLOGY';

select SALES AS TOP_FIVE_SALE FROM SUPER_STORE_DATA
ORDER BY SALES DESC
LIMIT 5;

SELECT REGION, sum(PROFIT) AS TOTAL_PROFIT
FROM SUPER_STORE_DATA
GROUP BY REGION;

SELECT * FROM SUPER_STORE_DATA order by PROFIT DESC;

SELECT CITY, sum(PROFIT) AS TOTAL_PROFIT
FROM SUPER_STORE_DATA
group by CITY
order by TOTAL_PROFIT desc
LIMIT 10;

select * FROM SUPER_STORE_DATA WHERE SALES > (select avg(SALES) FROM SUPER_STORE_DATA);

SELECT Category from SUPER_STORE_DATA where profit = 
(select min(profit) from SUPER_STORE_DATA);

select state, avg(sales) as avg_sale from SUPER_STORE_DATA where category = 'technology'
group by state;

select category from SUPER_STORE_DATA
group by category
order by sum(discount) asc limit 1;

select distinct((region)) from SUPER_STORE_DATA;
SELECT * FROM SUPER_STORE_DATA order by PROFIT DESC LIMIT 1 OFFSET 5;

SELECT 
    S1.region,
    S1.city,
    S2.city 
FROM 
    SUPER_STORE_DATA S1
INNER JOIN 
    SUPER_STORE_DATA S2 
ON 
    S1.region = S2.region AND S1.city <> S2.city
LIMIT 10;

SELECT S1.REGION, S1.CITY, S2.CITY FROM SUPER_STORE_DATA S1 inner join SUPER_STORE_DATA S2 ON S1.REGION = S2.REGION AND S1.CITY != S2.CITY LIMIT 5;